   const allAuthors = {
        'Шедеврум': {
            profileUrl: 'https://shedevrum.ai/text-to-image/',
            avatarUrl: 'data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBwgHBgkIBwgKCgkLDRYPDQwMDRsUFRAWIB0iIiAdHx8kKDQsJCYxJx8fLT0tMTU3Ojo6Iys/RD84QzQ5OjcBCgoKDQwNGg8PGjclHyU3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3NTc3Nzc3Mjc3Nzc1NzU3NzU3Mjc3NTc1NzI1N//AABEIABwAHAMBEQACEQEDEQH/xAAaAAACAwEBAAAAAAAAAAAAAAADBgEEBQIA/8QAKRAAAgIBAQYFBQAAAAAAAAAAAQIDBBEAEhMhMUFhBSJxgaEUIzJRkf/EABoBAAIDAQEAAAAAAAAAAAAAAAUGAgMEAAH/xAAqEQACAgAEBQEJAAAAAAAAAAABAgADBBExQQUTIVGRFBIiMkJhcaGxwf/aAAwDAQACEQMRAD8Ao2ZxX3TPgIzhGY9M8vnA99LtVRsJUa7R/wATiBhwrt8OeRPbPfzLdlFpU2M7IbMrruo2dQypkbWFzlmxnHrolRw0OgazMHtF7G8csS4rQQVG/wDPt9ZEghKRy1nZ4pBkEjl2zyPQ+40LsrNblDtDuAxnq6vbyyMHqE2wdqslunZikDFdyx8vPIHD5xqylilikd5g4mR6Rwd+kTmkvNYnryTvuYiVG8/LZ6Zx1xjR43kqIo0YIOxJ0Eeq88yRR0ErItAV/I7YDs4PFzx7jHvoHYitm5PvZwhhLWquUjSC1TG2cTRCaJo2Z1VuZRip/o1JGKnMSm+hL09h9InW6Nqz4xagV/vOzuc8iMZGPXgNF0uRag506RY9HaLmpU9evjbzNrwSY+JwRWSZYjCqxMUkxvSAOfbtrJiTyiUG/wCJq4XhEvHNbY+ZtawxjntdOgBUhFv6vZJn2dnaLHgP1jU+axTl7SgYasXG75tNT+tJNWrFUjMcIwrMWPqddZY1hzae04dKFKppnn5htQl0/9k=', // Ссылка на картинку
            sign: ''
        },
        'Ludo.ai': {
            profileUrl: 'https://app.ludo.ai/',
            avatarUrl: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABwAAAAcCAMAAABF0y+mAAAAulBMVEVHcExXhvVXhfVcfPRZgfRXhfRWiPVbfvRmZPNedvRcevRkafJib/NTkPZQlvZpaPNdePRRk/ZibPNgcvRib/NnYfJlZvJedvRdd/NuUvJ1Q/Bhc/RrWvJpXvJjbfNVivV2P/B1Q/BrWfFlaPJZgvRXhfR4PO97Ne9vUPBuUvFsVfFoYPJgcPRVivV3P/B3PvBwTfFvT/FxS/B3Pu9ed/R0RfB5Oe9tVPF6OO9wTvFpXfJ9Me9/K+5/LO9jkVs7AAAAPnRSTlMAW79X///I/nZe//DZk3MFw////yf////xCzIb//5A/+L/6Kjo1vMpW///6emGqP+3//9+mNaRxP/T1//8T5hYxugAAAEKSURBVHgBYiABAOqgBwWGYQCKom9GbWO2rf//rSVtMu/WPWUKxf9WKleqf61W/q31BtBo1n6jINJbmzX2Ukl+RQW0hspM06j+iON//bS6qBuG2sCPTMu2daKOa+KZ59N1EEZcm5nGSQAgbVFth1Q7uh57brNW6/aSRAL6rVZrgOFoTHQCWzcxdZp0qJIZMF+0UgXLFVWCtj41jFwJYp7S1ZpqG/y9VAvI87Ck2kb0ogrDTZqrV2fqOM0tWIvWjuhovCS3sntFbvtFpqslDiHTLTf/eMx0g9N4HJ7rsRkH3AaXS67Kibw2xlvXK9PWer3y8N6NIFcf+KtzfDfg6uNXm1zxp9s8Pfbx1h076iiLa8C0uwAAAABJRU5ErkJggg==',
            sign: ''
        },
		'pauliuw': {
            profileUrl: 'https://opengameart.org/users/pauliuw',
            avatarUrl: '',
            sign: 'plw'
        },
		'ravenmore': {
            profileUrl: 'https://ravenmore.itch.io/',
            avatarUrl: 'https://img.itch.zone/aW1nLzI0NDMzNDAyLnBuZw==/original/LI1xmf.png',
            sign: ''
        },
        
    };
    const assets = [
        { 
            id: 0, 
            types: ['Локации','Пиксельные'], 
            authors: ['Шедеврум'],
            name: 'Фентези локации', 
            desc: 'Набор задников для локаций игры, в 8битном стиле.', 
            previewImg: 'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fantasy%20RPG%20locations/castle1.jpg', 
            files: [
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fantasy%20RPG%20locations/tavern1.jpg',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fantasy%20RPG%20locations/tavern5.jpg',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fantasy%20RPG%20locations/temple1.jpg',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fantasy%20RPG%20locations/temple2.jpg',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fantasy%20RPG%20locations/tent.jpg',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fantasy%20RPG%20locations/tent_inside.jpg',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fantasy%20RPG%20locations/town_gate.jpg',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fantasy%20RPG%20locations/vilage_road1.jpg',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fantasy%20RPG%20locations/vilage_road2.jpg',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fantasy%20RPG%20locations/vilage_road3.jpg',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fantasy%20RPG%20locations/vilage_road4.jpg',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fantasy%20RPG%20locations/vilage_road5.jpg',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fantasy%20RPG%20locations/vilage_road6.jpg',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fantasy%20RPG%20locations/vilage_road7.jpg',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fantasy%20RPG%20locations/wood_house1.jpg',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fantasy%20RPG%20locations/wood_house2.jpg',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fantasy%20RPG%20locations/wood_house3.jpg',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fantasy%20RPG%20locations/wood_house4.jpg',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fantasy%20RPG%20locations/wood_house5.jpg',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fantasy%20RPG%20locations/castle1.jpg',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fantasy%20RPG%20locations/castle2.jpg',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fantasy%20RPG%20locations/cliffs.jpg',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fantasy%20RPG%20locations/dark_forest.jpg',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fantasy%20RPG%20locations/down_town_house1.jpg',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fantasy%20RPG%20locations/down_town_house2.jpg',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fantasy%20RPG%20locations/down_town1.jpg',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fantasy%20RPG%20locations/down_town2.jpg',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fantasy%20RPG%20locations/down_town3.jpg',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fantasy%20RPG%20locations/down_town4.jpg',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fantasy%20RPG%20locations/elf_forest1.jpg',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fantasy%20RPG%20locations/elf_forest2.jpg',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fantasy%20RPG%20locations/elf_forest3.jpg',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fantasy%20RPG%20locations/elf_forest4.jpg',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fantasy%20RPG%20locations/elf_forest5.jpg',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fantasy%20RPG%20locations/elf_forest6.jpg',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fantasy%20RPG%20locations/elf_forest7.jpg',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fantasy%20RPG%20locations/elf_house1.jpg',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fantasy%20RPG%20locations/elf_house2.jpg',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fantasy%20RPG%20locations/elf_house3.jpg',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fantasy%20RPG%20locations/elf_house4.jpg',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fantasy%20RPG%20locations/elf_house5.jpg',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fantasy%20RPG%20locations/elf_house6.jpg',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fantasy%20RPG%20locations/elf_vilage1.jpg',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fantasy%20RPG%20locations/elf_vilage2.jpg',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fantasy%20RPG%20locations/field1.jpg',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fantasy%20RPG%20locations/field2.jpg',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fantasy%20RPG%20locations/field3.jpg',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fantasy%20RPG%20locations/fire_cave.jpg',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fantasy%20RPG%20locations/fire_cave_enter.jpg',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fantasy%20RPG%20locations/forest_vilage.jpg',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fantasy%20RPG%20locations/forest1.jpg',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fantasy%20RPG%20locations/forest2.jpg',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fantasy%20RPG%20locations/forge1.jpg',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fantasy%20RPG%20locations/forge2.jpg',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fantasy%20RPG%20locations/ice_cave_enter1.jpg',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fantasy%20RPG%20locations/ice_cave_enter2.jpg',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fantasy%20RPG%20locations/ice_cave_enter3.jpg',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fantasy%20RPG%20locations/ice_cave1.jpg',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fantasy%20RPG%20locations/ice_cave2.jpg',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fantasy%20RPG%20locations/ice_cave3.jpg',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fantasy%20RPG%20locations/ice_cave4.jpg',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fantasy%20RPG%20locations/ice_cliffs1.jpg',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fantasy%20RPG%20locations/ice_cliffs2.jpg',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fantasy%20RPG%20locations/ice_cliffs3.jpg',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fantasy%20RPG%20locations/ice_cliffs4.jpg',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fantasy%20RPG%20locations/ice_forest1.jpg',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fantasy%20RPG%20locations/ice_forest2.jpg',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fantasy%20RPG%20locations/ice_vilage.jpg',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fantasy%20RPG%20locations/ice_vilage_house1.jpg',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fantasy%20RPG%20locations/ice_vilage_house2.jpg',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fantasy%20RPG%20locations/market_street1.jpg',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fantasy%20RPG%20locations/market_street2.jpg',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fantasy%20RPG%20locations/market_street3.jpg',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fantasy%20RPG%20locations/market_street4.jpg',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fantasy%20RPG%20locations/oak_forest1.jpg',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fantasy%20RPG%20locations/oak_forest2.jpg',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fantasy%20RPG%20locations/oak_forest3.jpg',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fantasy%20RPG%20locations/oak_forest4.jpg',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fantasy%20RPG%20locations/palace1.jpg',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fantasy%20RPG%20locations/palace2.jpg',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fantasy%20RPG%20locations/palace3.jpg',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fantasy%20RPG%20locations/spruce_forest1.jpg',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fantasy%20RPG%20locations/spruce_forest2.jpg',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fantasy%20RPG%20locations/stone_house_workbench1.jpg',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fantasy%20RPG%20locations/stone_house_workbench2.jpg',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fantasy%20RPG%20locations/stone_house1.jpg',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fantasy%20RPG%20locations/stone_house2.jpg',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fantasy%20RPG%20locations/stone_house3.jpg',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fantasy%20RPG%20locations/stone_house4.jpg',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fantasy%20RPG%20locations/stone_house5.jpg',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fantasy%20RPG%20locations/stone_house6.jpg',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fantasy%20RPG%20locations/stone_house7.jpg',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fantasy%20RPG%20locations/stone_house8.jpg',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fantasy%20RPG%20locations/stone_house9.jpg',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fantasy%20RPG%20locations/stone_house10.jpg',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fantasy%20RPG%20locations/stone_house11.jpg',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fantasy%20RPG%20locations/stone_house12.jpg',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fantasy%20RPG%20locations/stone_tower1.jpg',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fantasy%20RPG%20locations/stone_tower2.jpg',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fantasy%20RPG%20locations/street.jpg'
]
        },
        { 
            id: 0, 
            types: ['Бойцы', 'Пиксельные'],
            authors: ['Ludo.ai'],
            name: 'Боевые персонажи', 
            desc: 'Набор боевых персонажей со спрайтовой анимацией, в 8битном стиле.', 
            previewImg: 'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fighters/preview.png', 
            files: [
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fighters/dualist.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fighters/golem.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fighters/guardian.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fighters/gunner.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fighters/halberdier.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fighters/hunter.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fighters/paladin.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fighters/prist.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fighters/rogue.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fighters/scout.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fighters/thief.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fighters/warlock.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fighters/warrior.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Fighters/yeti.png'
]
        },
        { 
            id: 0, 
            types: ['Объекты', 'Пиксельные'], 
            authors: ['Ludo.ai'],
            name: 'Квестодатели, НПС, Торговцы', 
            desc: 'Набор персонажей, для взаимодействия на локациях, в 8битном стиле.', 
            previewImg: 'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Questgivers%2C%20NPCs%2C%20Vendors/preview.png', 
            files: [
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Questgivers%2C%20NPCs%2C%20Vendors/char1.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Questgivers%2C%20NPCs%2C%20Vendors/char2.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Questgivers%2C%20NPCs%2C%20Vendors/char3.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Questgivers%2C%20NPCs%2C%20Vendors/char4.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Questgivers%2C%20NPCs%2C%20Vendors/char5.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Questgivers%2C%20NPCs%2C%20Vendors/char6.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Questgivers%2C%20NPCs%2C%20Vendors/char7.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Questgivers%2C%20NPCs%2C%20Vendors/char8.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Questgivers%2C%20NPCs%2C%20Vendors/char9.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Questgivers%2C%20NPCs%2C%20Vendors/char10.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Questgivers%2C%20NPCs%2C%20Vendors/char11.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Questgivers%2C%20NPCs%2C%20Vendors/char12.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Questgivers%2C%20NPCs%2C%20Vendors/char13.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Questgivers%2C%20NPCs%2C%20Vendors/char14.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Questgivers%2C%20NPCs%2C%20Vendors/npc1.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Questgivers%2C%20NPCs%2C%20Vendors/npc2.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Questgivers%2C%20NPCs%2C%20Vendors/npc3.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Questgivers%2C%20NPCs%2C%20Vendors/npc4.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Questgivers%2C%20NPCs%2C%20Vendors/npc5.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Questgivers%2C%20NPCs%2C%20Vendors/npc6.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Questgivers%2C%20NPCs%2C%20Vendors/npc7.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Questgivers%2C%20NPCs%2C%20Vendors/npc8.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Questgivers%2C%20NPCs%2C%20Vendors/npc9.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Questgivers%2C%20NPCs%2C%20Vendors/npc10.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Questgivers%2C%20NPCs%2C%20Vendors/npc11.png',
	'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Questgivers%2C%20NPCs%2C%20Vendors/npc12.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Questgivers%2C%20NPCs%2C%20Vendors/vendor1.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Questgivers%2C%20NPCs%2C%20Vendors/vendor2.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Questgivers%2C%20NPCs%2C%20Vendors/vendor3.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Questgivers%2C%20NPCs%2C%20Vendors/vendor4.png',
	'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Questgivers%2C%20NPCs%2C%20Vendors/orc_char5.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Questgivers%2C%20NPCs%2C%20Vendors/troll_char1.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Questgivers%2C%20NPCs%2C%20Vendors/troll_char2.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Questgivers%2C%20NPCs%2C%20Vendors/troll_char3.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Questgivers%2C%20NPCs%2C%20Vendors/troll_char4.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Questgivers%2C%20NPCs%2C%20Vendors/troll_char5.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Questgivers%2C%20NPCs%2C%20Vendors/dwarf_char1.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Questgivers%2C%20NPCs%2C%20Vendors/dwarf_char2.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Questgivers%2C%20NPCs%2C%20Vendors/dwarf_char3.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Questgivers%2C%20NPCs%2C%20Vendors/dwarf_char4.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Questgivers%2C%20NPCs%2C%20Vendors/dwarf_char5.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Questgivers%2C%20NPCs%2C%20Vendors/dwarf_char6.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Questgivers%2C%20NPCs%2C%20Vendors/dwarf_char7.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Questgivers%2C%20NPCs%2C%20Vendors/dwarf_char8.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Questgivers%2C%20NPCs%2C%20Vendors/dwarf_char9.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Questgivers%2C%20NPCs%2C%20Vendors/dwarf_char10.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Questgivers%2C%20NPCs%2C%20Vendors/elf_char1.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Questgivers%2C%20NPCs%2C%20Vendors/elf_char2.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Questgivers%2C%20NPCs%2C%20Vendors/elf_char3.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Questgivers%2C%20NPCs%2C%20Vendors/elf_char4.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Questgivers%2C%20NPCs%2C%20Vendors/elf_char5.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Questgivers%2C%20NPCs%2C%20Vendors/elf_char6.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Questgivers%2C%20NPCs%2C%20Vendors/elf_char7.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Questgivers%2C%20NPCs%2C%20Vendors/elf_char8.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Questgivers%2C%20NPCs%2C%20Vendors/elf_char9.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Questgivers%2C%20NPCs%2C%20Vendors/elf_char10.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Questgivers%2C%20NPCs%2C%20Vendors/elf_char11.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Questgivers%2C%20NPCs%2C%20Vendors/elf_char12.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Questgivers%2C%20NPCs%2C%20Vendors/elf_char13.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Questgivers%2C%20NPCs%2C%20Vendors/elf_char14.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Questgivers%2C%20NPCs%2C%20Vendors/elf_char15.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Questgivers%2C%20NPCs%2C%20Vendors/elf_char16.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Questgivers%2C%20NPCs%2C%20Vendors/elf_char17.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Questgivers%2C%20NPCs%2C%20Vendors/elf_char18.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Questgivers%2C%20NPCs%2C%20Vendors/elf_char19.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Questgivers%2C%20NPCs%2C%20Vendors/elf_char20.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Questgivers%2C%20NPCs%2C%20Vendors/forest_elf_char1.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Questgivers%2C%20NPCs%2C%20Vendors/forest_elf_char2.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Questgivers%2C%20NPCs%2C%20Vendors/forest_elf_char3.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Questgivers%2C%20NPCs%2C%20Vendors/forest_elf_char4.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Questgivers%2C%20NPCs%2C%20Vendors/forest_elf_char5.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Questgivers%2C%20NPCs%2C%20Vendors/orc_char1.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Questgivers%2C%20NPCs%2C%20Vendors/orc_char2.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Questgivers%2C%20NPCs%2C%20Vendors/orc_char3.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Questgivers%2C%20NPCs%2C%20Vendors/orc_char4.png'
]
        },
        { 
            id: 0, 
            types: ['Объекты', 'Пиксельные'], 
            authors: ['Ludo.ai'],
            name: 'Декорации', 
            desc: 'Декор для локаций, Крафтовые станки, Квестовые объекты, в 8битном стиле.', 
            previewImg: 'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Decor/preview.png', 
            files: [
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Decor/alchemy1.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Decor/alchemy2.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Decor/alchemy3.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Decor/alchemy4.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Decor/alchemy5.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Decor/alchemy6.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Decor/alchemy7.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Decor/alchemy8.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Decor/decor1.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Decor/decor2.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Decor/decor3.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Decor/decor4.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Decor/decor5.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Decor/decor6.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Decor/decor7.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Decor/decor8.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Decor/decor9.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Decor/decor10.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Decor/decor11.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Decor/decor12.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Decor/decor13.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Decor/decor14.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Decor/decor15.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Decor/decor16.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Decor/decor17.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Decor/decor18.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Decor/decor19.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Decor/decor20.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Decor/decor21.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Decor/fountain1.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Decor/fountain2.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Decor/fountain3.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Decor/fountain4.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Decor/fountain5.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Decor/fountain6.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Decor/fountain7.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Decor/furniture1.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Decor/furniture2.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Decor/furniture3.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Decor/furniture4.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Decor/furniture5.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Decor/furniture6.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Decor/npc1.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Decor/npc2.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Decor/tree1.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Decor/tree2.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Decor/tree3.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Decor/tree4.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Decor/workbench1.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Decor/workbench2.png'
]
        },
		{ 
            id: 0, 
            types: ['Бафы', 'Пиксельные'], 
            authors: ['Ludo.ai'],
            name: 'Эффекты', 
            desc: 'Эффекты для бафов со спрайтовой анимацией, в 8битном стиле.', 
            previewImg: 'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Buff%20FX/preview.png', 
            files: [
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Buff%20FX/burn3.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Buff%20FX/dodecahedron.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Buff%20FX/healing.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Buff%20FX/irritation.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Buff%20FX/poisoned.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Buff%20FX/root.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Buff%20FX/shield.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Buff%20FX/stun.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Buff%20FX/stun2.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Buff%20FX/vanish.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Buff%20FX/wings.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Buff%20FX/blood.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Buff%20FX/blooded.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Buff%20FX/burn1.png',
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Buff%20FX/burn2.png'
]
        },
		{ 
            id: 0, 
            types: ['Способности', 'Предметы'], 
            authors: ['pauliuw'],
            name: 'Modified And Cliped Magic, Skill & Item Icons', 
            desc: `Скачать архив можно по ссылке: https://opengameart.org/content/modified-and-cliped-magic-skill-item-icons
			
			Hello all :)

I had cliped from the borders all of the icons from my first submission Skill, item and spell icons and modified most of them. Modifications is made whit a crappy mouse(cause my drawing tablet is broken) so some of them may not look so good. In total there is 576 icons, but some of them may look very similar and some is just with changed color, i included original(cliped from borders) images too. The sources is in tif format, cause i don't know if .psd is readable by most of image editors. Sources do not includes the layers from original images, cause those are lost, and the images in sources is different sizes so if you want them in other size, you will have to resize them your self. I have resized them to 32x32, 48x48, 64x64, 128x128 and 256x256, but uploaded only 64x64 cause the size of this submission would be to big, but if there is a need to upload other sizes i could do it. If you dont like the color or some added layers, you can easly recolor/remove it. Have fun! :)

 

P.S. i will get a new drawing tablet after a month or so and i need to know if you like this style icons, cause i want to make more of them, but this time with full sources.`, 
            previewImg: 'https://opengameart.org/sites/default/files/full.png', 
            files: [

]
        },
		{ 
            id: 0, 
            types: ['Предметы'], 
            authors: ['ravenmore'],
            name: 'Fantasy Icon Pack by Ravenmore', 
            desc: `Скачать архив можно по ссылке: https://opengameart.org/content/fantasy-icon-pack-by-ravenmore-0
			
			Ravenmore's Icon Pack 2.0

Contains 29 hand painted icons.

+ 12 "upgraded versions" for weapons and armor

- transparent .png in 512x512, 128x128 and 64x64

- .psd source file (512x512)

Icons designed for a dark background.

Check out ravenmore.itch.io for more free things! =)

Attribution Instructions: 
Drop a link to ravenmore.itch.io, that's all ;) Cheers!`, 
            previewImg: 'https://opengameart.org/sites/default/files/preview2_13.png', 
            files: [

]
        },
		
		{ 
            id: 0, 
            types: ['Шаги', 'звуки'], 
            authors: ['Ludo.ai'],
            name: 'Звуки шагов', 
            desc: 'Звуки шагов по 7 поверхностям', 
            previewImg: 'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Step%20sounds/preview.png', 
            files: [
    'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Step%20sounds/paving.png',
	'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Step%20sounds/paving1.mp3',
	'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Step%20sounds/paving2.mp3',
	'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Step%20sounds/paving3.mp3',
	'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Step%20sounds/paving4.mp3',
	'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Step%20sounds/paving5.mp3',
	'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Step%20sounds/dirt.png',
	'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Step%20sounds/dirt1.mp3',
	'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Step%20sounds/dirt2.mp3',
	'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Step%20sounds/dirt3.mp3',
	'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Step%20sounds/dirt4.mp3',
	'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Step%20sounds/dirt5.mp3',
	'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Step%20sounds/grass.png',
	'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Step%20sounds/grass1.mp3',
	'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Step%20sounds/grass2.mp3',
	'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Step%20sounds/grass3.mp3',
	'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Step%20sounds/grass4.mp3',
	'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Step%20sounds/grass5.mp3',
	'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Step%20sounds/mud.png',
	'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Step%20sounds/mud1.mp3',
	'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Step%20sounds/mud2.mp3',
	'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Step%20sounds/mud3.mp3',
	'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Step%20sounds/mud4.mp3',
	'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Step%20sounds/mud5.mp3',
	'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Step%20sounds/water.png',
	'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Step%20sounds/water1.mp3',
	'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Step%20sounds/water2.mp3',
	'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Step%20sounds/water3.mp3',
	'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Step%20sounds/water4.mp3',
	'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Step%20sounds/water5.mp3',
	'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Step%20sounds/snow.png',
	'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Step%20sounds/snow1.mp3',
	'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Step%20sounds/snow2.mp3',
	'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Step%20sounds/snow3.mp3',
	'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Step%20sounds/snow4.mp3',
	'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Step%20sounds/snow5.mp3',
	'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Step%20sounds/metal.png',
	'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Step%20sounds/metal1.mp3',
	'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Step%20sounds/metal2.mp3',
	'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Step%20sounds/metal3.mp3',
	'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Step%20sounds/metal4.mp3',
	'https://raw.githubusercontent.com/proginvert/1D-RPG-Constructor/refs/heads/main/Assets/Step%20sounds/metal5.mp3',

]
        },
		
    ];
